version: '3' 
services: 
  db: 
    image: mariadb 
    container_name: interaction
    healthcheck:
      test: "/usr/bin/mariadb --user=root --password=123 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    env_file:
      - mariadb.env
    ports: 
      - 3310:3306
    volumes: 
    - ./interaction.sql:/docker-entrypoint-initdb.d/interaction.sql
