version: '3' 
services: 
  db: 
    image: mariadb 
    container_name: service
    healthcheck:
      test: "/usr/bin/mariadb --user=root --password=123 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    env_file:
      - mariadb.env
    ports: 
      - 3307:3306 
    volumes: 
    - ./service.sql:/docker-entrypoint-initdb.d/service.sql
